### PR TITLE
Created JavaScript -Functions and Arrays

### PR DESCRIPTION
**Pull request by kr84abhijeet**
hello,
I'm Kumar Abhijeet , github id- kr84abhijeet
I've added notes about Javascript -Functions and Arrays in the repo
Kindly consider it 
Thank You

### CODE REVIEW

**Comment by TKirtan** [comment]
Please use proper markdown format and improve readability of your files.

**Comment by kr84abhijeet** [comment]
Sir, I've done the changes 
Kindly consider it 
Thank you

**Comment by kr84abhijeet** [comment]
Sir,
Kindly consider my contribution
For this I'll be very grateful to you
Thank you

**Comment by kr84abhijeet** [comment]
Sir,
Kindly consider my contribution 
For this I'll be greatful to you
Thank you

**Pull request merged**
